# Generated by Django 4.0 on 2022-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetask',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='basetask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
