# Generated by Django 4.0 on 2022-04-17 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_basetask_data_alter_basetask_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 17, 9, 29, 30, 741394, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
