# Generated by Django 4.0 on 2022-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_basetask_created_at_basetask_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetask',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
