# Generated by Django 4.0 on 2022-04-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_basetask_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetask',
            name='data',
        ),
        migrations.CreateModel(
            name='BaseParsingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parser_app.basetask')),
            ],
        ),
    ]
