# Generated by Django 4.0 on 2022-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_remove_basetask_data_baseparsingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetask',
            name='is_active',
        ),
        migrations.AddField(
            model_name='basetask',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
